version: '3'
services:
  art-ros-master:
    image: "ros:indigo-ros-core"
    command: "roscore"
    network_mode: "host"
  art-mavros-node:
    build: "./mavros/"
    command: "rosrun mavros mavros_node _fcu_url:=udp://:14550@ _gcs_url:=udp://:14551@"
    network_mode: "host"
  art-arducopter:
    build: "./main_ardupilot/"
    working_dir: "/home/robot/ardupilot/ArduCopter"
    command: "sim_vehicle.py -D -f gazebo-iris "
    volumes:
       - /tmp/.X11-unix:/tmp/.X11-unix
    tty: true
    stdin_open: true
    environment:
        - ROS_MASTER_URI=http://art-ros-master:11311/
        - DISPLAY=unix:0
    ports:
      - "5760:5760"
    network_mode: "host"
